// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Passagens.Search.Infrastructure.Persistence.Context;

#nullable disable

namespace Passagens.Search.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20260225135848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AeroportoDestino")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("AeroportoOrigem")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataIda")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVolta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("pesquisas", (string)null);
                });

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PesquisaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PesquisadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PesquisaId");

                    b.ToTable("pesquisa_snapshots", (string)null);
                });

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.VooEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Companhia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroVoo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("Valor");

                    b.ToTable("voos", (string)null);
                });

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaSnapshotEntity", b =>
                {
                    b.HasOne("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaEntity", "Pesquisa")
                        .WithMany("Snapshots")
                        .HasForeignKey("PesquisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesquisa");
                });

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.VooEntity", b =>
                {
                    b.HasOne("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaSnapshotEntity", "Snapshot")
                        .WithMany("Voos")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaEntity", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Passagens.Search.Infrastructure.Persistence.Entities.PesquisaSnapshotEntity", b =>
                {
                    b.Navigation("Voos");
                });
#pragma warning restore 612, 618
        }
    }
}
